module Layered
  module Assistant
    module Generators
      class InstallGenerator < Rails::Generators::Base
        desc "Install layered-ui-assistant into the host application"

        def self.source_root
          Layered::Assistant::Engine.root
        end

        def verify_layered_ui_dependency
          application_css = "app/assets/tailwind/application.css"
          application_js = "app/javascript/application.js"

          css_ok = File.exist?(application_css) && File.read(application_css).match?(%r{@import\s+['"]\.?/?layered_ui['"]})
          js_ok = File.exist?(application_js) && File.read(application_js).match?(%r{import\s+['"]layered_ui['"]})

          unless css_ok && js_ok
            say "layered-ui-rails is not installed yet - installing now...", :yellow
            invoke "layered:ui:install"
          end
        end

        def copy_css
          source_path = File.join(self.class.source_root, "app/assets/tailwind/layered/assistant/styles.css")
          source_content = File.read(source_path)

          header = <<~CSS
            /*
             * layered-assistant-rails v#{Layered::Assistant::VERSION}
             *
             * This file was automatically generated by the layered:assistant:install generator.
             * Do not modify directly. To update, re-run: bin/rails generate layered:assistant:install
             */

          CSS

          create_file "app/assets/tailwind/layered_assistant.css", header + source_content, force: true
        end

        def add_css_import
          application_css = "app/assets/tailwind/application.css"

          return unless File.exist?(application_css)

          content = File.read(application_css)
          import_line = '@import "./layered_assistant";'

          return if content.match?(%r{@import\s+['"]\.?/?layered_assistant['"]})

          # Insert after the layered_ui import (which must already be present)
          inject_into_file application_css, "\n#{import_line}", after: %r{@import\s+['"]\.?/?layered_ui['"];?}
          say "Added import to #{application_css}", :green
        end

        def add_js_import
          application_js = "app/javascript/application.js"

          return unless File.exist?(application_js)

          content = File.read(application_js)
          import_line = 'import "layered_assistant"'

          return if content.match?(%r{import\s+['"]layered_assistant['"]})

          # Insert after the layered_ui import (which must already be present)
          inject_into_file application_js, "\n#{import_line}", after: %r{import\s+['"]layered_ui['"];?}
          say "Added import to #{application_js}", :green
        end

        def copy_initializer
          initializer_path = "config/initializers/layered_assistant.rb"

          return if File.exist?(initializer_path)

          template_path = File.expand_path("templates/initializer.rb", __dir__)
          create_file initializer_path, File.read(template_path)
          say "Created #{initializer_path}", :green
        end

        def mount_engine
          routes_file = "config/routes.rb"

          return unless File.exist?(routes_file)

          content = File.read(routes_file)
          mount_line = 'mount Layered::Assistant::Engine => "/layered/assistant"'

          return if content.include?("Layered::Assistant::Engine")

          inject_into_file routes_file, "  #{mount_line}\n\n", after: "Rails.application.routes.draw do\n"
          say "Mounted engine in #{routes_file}", :green
        end

        def copy_migrations
          invoke "layered:assistant:migrations"
        end

        def show_instructions
          say ""
          say "layered-assistant-rails installed successfully", :green
          say ""
          say "Next steps:", :yellow
          say "  1. Run bin/rails db:migrate"
          say "  2. Configure authorization in config/initializers/layered_assistant.rb"
          say "  3. Routes return 403 until you uncomment an authorize block"
          say "  4. Visit /layered/assistant to get started"
          say ""
        end
      end
    end
  end
end
